version: "3"
services:
  fastapi:
    build:
      context: ./
      dockerfile: ./fastapi.Dockerfile
    ports:
      - "8000:8000"
    networks:
      - internal
    volumes:
      - ./FastAPI/:/home/FastAPI/
      - ./requirements.txt:/home/requirements.txt
    entrypoint:
      ["bash", "-c", "cd /home/FastAPI && uvicorn main:app --workers 2"]
    extra_hosts:
      - "host.docker.internal:host-gateway"
  nginx:
    build:
      context: ./
      dockerfile: ./nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - internal
    volumes:
      - ./React/audiosplice-app/:/home/React/
    depends_on:
      - fastapi
networks:
  internal:
    driver: bridge
